src/Entity/Items.php
<?php

namespace App\Entity;

use App\Repository\ItemsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ItemsRepository::class)
 */
class Items
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank
     * @Assert\Length(
     *  min = 2,
     *  maxMessage = "Item title must have {{ 2 }} characters and above"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Assert\NotBlank
     * @Assert\Length(
     *  min = 2,
     *  maxMessage = "Item description must have {{ 2 }} characters and above"
     * )
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @Assert\NotBlank
     * @Assert\Positive
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/Logs.php
<?php

namespace App\Entity;

use App\Repository\LogsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LogsRepository::class)
 */
class Logs
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $order_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $issue_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $log_type;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $staff_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $staff_username;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $issue_type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $issue_reason;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $box_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $shipping_company;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tracking_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $proof;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderId(): ?int
    {
        return $this->order_id;
    }

    public function setOrderId(int $order_id): self
    {
        $this->order_id = $order_id;

        return $this;
    }

    public function getIssueId(): ?int
    {
        return $this->issue_id;
    }

    public function setIssueId(?int $issue_id): self
    {
        $this->issue_id = $issue_id;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getLogType(): ?string
    {
        return $this->log_type;
    }

    public function setLogType(string $log_type): self
    {
        $this->log_type = $log_type;

        return $this;
    }

    public function getStaffId(): ?int
    {
        return $this->staff_id;
    }

    public function setStaffId(?int $staff_id): self
    {
        $this->staff_id = $staff_id;

        return $this;
    }

    public function getStaffUsername(): ?string
    {
        return $this->staff_username;
    }

    public function setStaffUsername(?string $staff_username): self
    {
        $this->staff_username = $staff_username;

        return $this;
    }

    public function getIssueType(): ?string
    {
        return $this->issue_type;
    }

    public function setIssueType(?string $issue_type): self
    {
        $this->issue_type = $issue_type;

        return $this;
    }

    public function getIssueReason(): ?string
    {
        return $this->issue_reason;
    }

    public function setIssueReason(?string $issue_reason): self
    {
        $this->issue_reason = $issue_reason;

        return $this;
    }

    public function getBoxId(): ?string
    {
        return $this->box_id;
    }

    public function setBoxId(?string $box_id): self
    {
        $this->box_id = $box_id;

        return $this;
    }

    public function getShippingCompany(): ?string
    {
        return $this->shipping_company;
    }

    public function setShippingCompany(?string $shipping_company): self
    {
        $this->shipping_company = $shipping_company;

        return $this;
    }

    public function getTrackingNumber(): ?string
    {
        return $this->tracking_number;
    }

    public function setTrackingNumber(?string $tracking_number): self
    {
        $this->tracking_number = $tracking_number;

        return $this;
    }

    public function getProof(): ?string
    {
        return $this->proof;
    }

    public function setProof(?string $proof): self
    {
        $this->proof = $proof;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/users/manager/index.html.twig
{% extends('base.html.twig') %}

{% block body %}
<h1>Manager Dashboard!</h1>

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <form method="get" action="{{ path('manager_filter') }}">
            <div class="form-group">
                <label>Filter by status</label>
                <select name="status" class="form-control">
                <option value="DEFAULT">Choose Status</option>
                <option value="ALL">All Orders</option>
                <option value="ORDER_RECEIVED">Order Received</option>
                <option value="ORDER_CANCELED">Order Canceled</option>
                <option value="ORDER_PROCESSING">Order Processing</option>
                <option value="ORDER_READY_TO_SHIP">Order Ready to Ship</option>
                <option value="ORDER_SHIPPED">Order Shipped</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
        </form>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <form method="get" action="{{ path('manager_search') }}">
            <div class="form-group">
                <label for="exampleInputEmail1">Search by order ID</label>
                <input type="number" class="form-control" name="orderId" placeholder="Enter order ID to search for." required>
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
      </div>
    </div>
  </div>
  <div class="col-sm-12">
  <div style="height: 30px"></div>
    <a href="{{ path('management_index') }}" class="btn btn-dark">Refresh List</a>
  </div>

  </div>



<div style="height: 30px;"></div>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Items</th>
        <th scope="col">Status</th>
        <th scope="col">Total Amount</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
          <tr>
            <th scope="row">{{ order.id }}</th>
            <td>
            {% for item in order.orderItems %}
              {{ item.item.title }},
            {% endfor %}
            </td>
            <td>{{ order.status }}</td>
            <td>{{ order.total }}</td>
            <td><a href="{{ path('management_view_order', {id: order.id}) }}" class="btn btn-info">View</a></td>
          </tr>
      {% endfor %}
      
    </tbody>
  </table>
  
</div>
<div>
    {{ knp_pagination_render(orders) }}
</div>


{% endblock %}

templates/users/manager/order_details.html.twig
{% extends('base.html.twig') %}

{% block body %}

<h5>About order: #{{order.id}}</h5>

<div style="height: 40px"></div>

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Items</h5>
        <p class="card-text">
          {% for item in order.orderItems %}
            {{ item.item.title }},
          {% endfor %}
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Order status</h5>
        <p class="card-text">{{ order.status }}</p>
      </div>
    </div>
  </div>

  
  <div class="col-sm-12">
   <div style="height: 30px"></div>
  </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Shipping Address</h5>
        <p class="card-text">{{ order.shippingdetails }}</p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Discount</h5>
        <p class="card-text">{{ order.discount }}</p>
      </div>
    </div>
  </div>

   <div class="col-sm-12">
   <div style="height: 30px"></div>
  </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Total Cost</h5>
        <p class="card-text">${{ order.total }}</p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Date</h5>
        <p class="card-text">{{ order.createdAt.format('Y-m-d H:i:s') }}</p>
      </div>
    </div>
  </div>

    <div class="col-sm-12">
        <div style="height: 20px"></div>
        <h5>Package Details</h5>
        <div style="height: 10px"></div>
    </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Box ID</h5>
        {% if package is null or package.boxId is null %}
            <span class="badge badge-secondary">No box ID yet</span>
        {% endif %}

        {% if package != null and  package.boxId != null %}
                <p class="card-text">{{ package.boxId }}</p>
        {% endif %}
        
      </div>
    </div>
  </div>

  

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Tracking Number</h5>
         {% if package is null or package.trackingNumber is null %}
             <span class="badge badge-secondary">No tracking numeber yet</span>
        {% endif %}

        {% if package != null and  package.trackingNumber != null %}
                <p class="card-text">{{ package.trackingNumber }}</p>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="col-sm-12">
   <div style="height: 30px"></div>
  </div>


  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Proof</h5>
        {% if package is null or package.proof is null %}
             <span class="badge badge-secondary">Proof would be available after shipment is completed</span>
        {% endif %}

        {% if package != null and  package.proof != null %}
                <p class="card-text">{{ package.proof }}</p>
        {% endif %}
      </div>
    </div>
  </div>


  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">

        {% if package != null and  package.updatedAt != null %}

            <h5 class="card-title">Last updated</h5>
            <p class="card-text">{{ package.updatedAt.format('Y-m-d H:i:s') }}</p>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="col-sm-12">
   <div style="height: 30px"></div>
  </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Shipping Company</h5>
        {% if package is null or package.shippingCompany is null %}
             <span class="badge badge-secondary">No company assigned yet</span>
        {% endif %}

        {% if package != null and  package.shippingCompany != null %}
                <p class="card-text">{{ package.shippingCompany }}</p>
        {% endif %}


      </div>
    </div>
  </div>

</div>

<div style="height: 30px"></div>

<h5>Issues</h5>
{% if issues is empty %}
    <span class="badge badge-secondary">No issues have been reported for this order</span>
{% endif %}

<ul class="list-group">
    {% for issue in issues %}
        <li class="list-group-item"><span class="badge badge-warning"> {{ issue.type.type }} </span> - {{ issue.reason }} <br/><span class="text-muted">{{ issue.createdAt.format('Y-m-d H:i:s') }}</span></li>
    {% endfor %}
</ul>

<div style="height: 40px;"></div>

<h5>Order Log</h5>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Status</th>
        <th scope="col">Log Message</th>
      </tr>
    </thead>
    <tbody>
      {% for log in logs %}
          <tr>
            <th scope="row">{{ log.createdAt.format('Y-m-d') }} at {{ log.createdAt.format('H:i:s') }}</th>
            <td>{{ log.status }}</td>
            <td>

                {% if log.logType == 'new' %}
                    Order #{{ log.orderId }} has been received by the system.
                {% endif %}

                {% if log.logType == 'processing' %}
                    Order #{{ log.orderId }} has been changed to PROCESSING by {{ log.staffUsername }} ({{ log.staffId }})
                {% endif %}

                {% if log.logType == 'reprocessing' %}
                    Order #{{ log.orderId }} has been changed to PROCESSING by {{ log.staffUsername }} ({{ log.staffId }}) with reason: {{ log.issueType }} ({{ log.issueReason }})
                {% endif %}

                {% if log.logType == 'ready' %}
                    Order #{{ log.orderId }} has been changed to READY TO SHIP by {{ log.staffUsername }} ({{ log.staffId }}) with BOX_ID: {{ log.boxId }}
                {% endif %}

                {% if log.logType == 'shipped' %}
                    Order #{{ log.orderId }} has been changed to SHIPPED by {{ log.staffUsername }} ({{ log.staffId }}) with AWB: #{{ log.trackingNumber }} by {{ log.shippingCompany }} <a href="{{ path('download_file', {filename: log.proof}) }}">[View Label]</a> 
                {% endif %}

                {% if log.logType == 'canceled' %}
                    Order #{{ log.orderId }} has been cancelled.
                {% endif %}
        
                {# {% if log.proof != null %}
                    <a href="{{ path('download_file', {filename: log.proof}) }}">View Proof File</a>
                {% endif %} #}
            </td>
          </tr>
      {% endfor %}
      
    </tbody>
  </table>
</div>

<div style="height: 100px"></div>



{% endblock %}